/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro;

import com.cohesionforce.avro.AbstractAvroSchemaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AvroSchemaRuntimeModule extends AbstractAvroSchemaRuntimeModule {
}
