/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro;

import com.cohesionforce.avro.AvroSchemaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AvroSchemaStandaloneSetup extends AvroSchemaStandaloneSetupGenerated {
  public static void doSetup() {
    new AvroSchemaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
