/*
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.ui.tests;

import com.cohesionforce.avro.ui.internal.AvroActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AvroSchemaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AvroActivator.getInstance().getInjector("com.cohesionforce.avro.AvroSchema");
	}

}
