/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.ui;

import com.cohesionforce.avro.ui.AbstractAvroSchemaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AvroSchemaUiModule extends AbstractAvroSchemaUiModule {
  public AvroSchemaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
