/*
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AvroSchemaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/cohesionforce/avro/parser/antlr/internal/InternalAvroSchema.tokens");
	}
}
