/*
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.ide


/**
 * Use this class to register ide components.
 */
class AvroSchemaIdeModule extends AbstractAvroSchemaIdeModule {
}
