/*
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAvroSchemaValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.cohesionforce.avro.avroSchema.AvroSchemaPackage.eINSTANCE);
		return result;
	}
}
