/*
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.ui;

import com.cohesionforce.avro.ui.internal.AvroActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AvroSchemaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(AvroActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		AvroActivator activator = AvroActivator.getInstance();
		return activator != null ? activator.getInjector(AvroActivator.COM_COHESIONFORCE_AVRO_AVROSCHEMA) : null;
	}

}
