/*
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.ide.contentassist.antlr;

import com.cohesionforce.avro.ide.contentassist.antlr.internal.InternalAvroSchemaParser;
import com.cohesionforce.avro.services.AvroSchemaGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AvroSchemaParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AvroSchemaGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AvroSchemaGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAvroSchemaAccess().getTypesAlternatives_0(), "rule__AvroSchema__TypesAlternatives_0");
			builder.put(grammarAccess.getUnionMemberAccess().getAlternatives(), "rule__UnionMember__Alternatives");
			builder.put(grammarAccess.getFieldAccess().getNameAlternatives_6_0(), "rule__Field__NameAlternatives_6_0");
			builder.put(grammarAccess.getFieldAccess().getAlternatives_13(), "rule__Field__Alternatives_13");
			builder.put(grammarAccess.getArrayTypeAccess().getAlternatives_13(), "rule__ArrayType__Alternatives_13");
			builder.put(grammarAccess.getMapTypeAccess().getAlternatives_13(), "rule__MapType__Alternatives_13");
			builder.put(grammarAccess.getPrimitiveAccess().getTypeAlternatives_1_0(), "rule__Primitive__TypeAlternatives_1_0");
			builder.put(grammarAccess.getUnionTypeAccess().getGroup(), "rule__UnionType__Group__0");
			builder.put(grammarAccess.getUnionTypeAccess().getGroup_2(), "rule__UnionType__Group_2__0");
			builder.put(grammarAccess.getUnionMemberAccess().getGroup_6(), "rule__UnionMember__Group_6__0");
			builder.put(grammarAccess.getJsonTypeAccess().getGroup(), "rule__JsonType__Group__0");
			builder.put(grammarAccess.getRecordTypeAccess().getGroup(), "rule__RecordType__Group__0");
			builder.put(grammarAccess.getRecordTypeAccess().getGroup_16(), "rule__RecordType__Group_16__0");
			builder.put(grammarAccess.getFieldListAccess().getGroup(), "rule__FieldList__Group__0");
			builder.put(grammarAccess.getFieldListAccess().getGroup_1(), "rule__FieldList__Group_1__0");
			builder.put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
			builder.put(grammarAccess.getFieldAccess().getGroup_13_2(), "rule__Field__Group_13_2__0");
			builder.put(grammarAccess.getEnumTypeAccess().getGroup(), "rule__EnumType__Group__0");
			builder.put(grammarAccess.getEnumTypeAccess().getGroup_22(), "rule__EnumType__Group_22__0");
			builder.put(grammarAccess.getEnumTypeAccess().getGroup_23(), "rule__EnumType__Group_23__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup(), "rule__ArrayType__Group__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup_13_2(), "rule__ArrayType__Group_13_2__0");
			builder.put(grammarAccess.getMapTypeAccess().getGroup(), "rule__MapType__Group__0");
			builder.put(grammarAccess.getMapTypeAccess().getGroup_13_2(), "rule__MapType__Group_13_2__0");
			builder.put(grammarAccess.getFixedTypeAccess().getGroup(), "rule__FixedType__Group__0");
			builder.put(grammarAccess.getPrimitiveAccess().getGroup(), "rule__Primitive__Group__0");
			builder.put(grammarAccess.getNamespaceAccess().getGroup(), "rule__Namespace__Group__0");
			builder.put(grammarAccess.getNamespaceAccess().getGroup_1(), "rule__Namespace__Group_1__0");
			builder.put(grammarAccess.getAvroSchemaAccess().getTypesAssignment(), "rule__AvroSchema__TypesAssignment");
			builder.put(grammarAccess.getUnionTypeAccess().getTypesAssignment_1(), "rule__UnionType__TypesAssignment_1");
			builder.put(grammarAccess.getUnionTypeAccess().getTypesAssignment_2_1(), "rule__UnionType__TypesAssignment_2_1");
			builder.put(grammarAccess.getUnionMemberAccess().getRecordRefAssignment_6_1(), "rule__UnionMember__RecordRefAssignment_6_1");
			builder.put(grammarAccess.getJsonTypeAccess().getTypeAssignment_6(), "rule__JsonType__TypeAssignment_6");
			builder.put(grammarAccess.getRecordTypeAccess().getNameAssignment_14(), "rule__RecordType__NameAssignment_14");
			builder.put(grammarAccess.getRecordTypeAccess().getNamespaceAssignment_16_6(), "rule__RecordType__NamespaceAssignment_16_6");
			builder.put(grammarAccess.getRecordTypeAccess().getFieldListAssignment_23(), "rule__RecordType__FieldListAssignment_23");
			builder.put(grammarAccess.getFieldListAccess().getFieldsAssignment_0(), "rule__FieldList__FieldsAssignment_0");
			builder.put(grammarAccess.getFieldListAccess().getFieldsAssignment_1_1(), "rule__FieldList__FieldsAssignment_1_1");
			builder.put(grammarAccess.getFieldAccess().getNameAssignment_6(), "rule__Field__NameAssignment_6");
			builder.put(grammarAccess.getFieldAccess().getPrimitiveAssignment_13_0(), "rule__Field__PrimitiveAssignment_13_0");
			builder.put(grammarAccess.getFieldAccess().getRecordAssignment_13_1(), "rule__Field__RecordAssignment_13_1");
			builder.put(grammarAccess.getFieldAccess().getRecordRefAssignment_13_2_1(), "rule__Field__RecordRefAssignment_13_2_1");
			builder.put(grammarAccess.getFieldAccess().getEtypeAssignment_13_3(), "rule__Field__EtypeAssignment_13_3");
			builder.put(grammarAccess.getFieldAccess().getArrayAssignment_13_4(), "rule__Field__ArrayAssignment_13_4");
			builder.put(grammarAccess.getFieldAccess().getMapAssignment_13_5(), "rule__Field__MapAssignment_13_5");
			builder.put(grammarAccess.getFieldAccess().getFixedAssignment_13_6(), "rule__Field__FixedAssignment_13_6");
			builder.put(grammarAccess.getFieldAccess().getUnionAssignment_13_7(), "rule__Field__UnionAssignment_13_7");
			builder.put(grammarAccess.getEnumTypeAccess().getNameAssignment_14(), "rule__EnumType__NameAssignment_14");
			builder.put(grammarAccess.getEnumTypeAccess().getSymbolsAssignment_22_1(), "rule__EnumType__SymbolsAssignment_22_1");
			builder.put(grammarAccess.getEnumTypeAccess().getSymbolsAssignment_23_2(), "rule__EnumType__SymbolsAssignment_23_2");
			builder.put(grammarAccess.getArrayTypeAccess().getPrimitiveAssignment_13_0(), "rule__ArrayType__PrimitiveAssignment_13_0");
			builder.put(grammarAccess.getArrayTypeAccess().getRecordAssignment_13_1(), "rule__ArrayType__RecordAssignment_13_1");
			builder.put(grammarAccess.getArrayTypeAccess().getRecordRefAssignment_13_2_1(), "rule__ArrayType__RecordRefAssignment_13_2_1");
			builder.put(grammarAccess.getArrayTypeAccess().getEtypeAssignment_13_3(), "rule__ArrayType__EtypeAssignment_13_3");
			builder.put(grammarAccess.getMapTypeAccess().getPrimitiveAssignment_13_0(), "rule__MapType__PrimitiveAssignment_13_0");
			builder.put(grammarAccess.getMapTypeAccess().getRecordAssignment_13_1(), "rule__MapType__RecordAssignment_13_1");
			builder.put(grammarAccess.getMapTypeAccess().getRecordRefAssignment_13_2_1(), "rule__MapType__RecordRefAssignment_13_2_1");
			builder.put(grammarAccess.getMapTypeAccess().getEtypeAssignment_13_3(), "rule__MapType__EtypeAssignment_13_3");
			builder.put(grammarAccess.getMapTypeAccess().getAtypeAssignment_13_4(), "rule__MapType__AtypeAssignment_13_4");
			builder.put(grammarAccess.getFixedTypeAccess().getNameAssignment_9(), "rule__FixedType__NameAssignment_9");
			builder.put(grammarAccess.getFixedTypeAccess().getSizeAssignment_17(), "rule__FixedType__SizeAssignment_17");
			builder.put(grammarAccess.getPrimitiveAccess().getTypeAssignment_1(), "rule__Primitive__TypeAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AvroSchemaGrammarAccess grammarAccess;

	@Override
	protected InternalAvroSchemaParser createParser() {
		InternalAvroSchemaParser result = new InternalAvroSchemaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AvroSchemaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AvroSchemaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
