/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.validation;

import com.cohesionforce.avro.validation.AbstractAvroSchemaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AvroSchemaValidator extends AbstractAvroSchemaValidator {
}
