/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.ui.contentassist;

import com.cohesionforce.avro.ui.contentassist.AbstractAvroSchemaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AvroSchemaProposalProvider extends AbstractAvroSchemaProposalProvider {
}
