/*
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAvroSchemaScopeProvider extends DelegatingScopeProvider {
}
