/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.ide;

import com.cohesionforce.avro.AvroSchemaRuntimeModule;
import com.cohesionforce.avro.AvroSchemaStandaloneSetup;
import com.cohesionforce.avro.ide.AvroSchemaIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AvroSchemaIdeSetup extends AvroSchemaStandaloneSetup {
  @Override
  public Injector createInjector() {
    AvroSchemaRuntimeModule _avroSchemaRuntimeModule = new AvroSchemaRuntimeModule();
    AvroSchemaIdeModule _avroSchemaIdeModule = new AvroSchemaIdeModule();
    return Guice.createInjector(Modules2.mixin(_avroSchemaRuntimeModule, _avroSchemaIdeModule));
  }
}
