/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.ide;

import com.cohesionforce.avro.ide.AbstractAvroSchemaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AvroSchemaIdeModule extends AbstractAvroSchemaIdeModule {
}
