/*
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.tests

import com.cohesionforce.avro.avroSchema.AvroSchema
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(AvroSchemaInjectorProvider)
class AvroSchemaParsingTest {
	@Inject
	ParseHelper<AvroSchema> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
{"type":"record","name":"Addressable","namespace":"org.eclipse.emf.examples.extlibrary.avro","fields":[
	{"name":"address","type":["null","string"]}
]}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
