/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.avroSchema;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.cohesionforce.avro.avroSchema.AvroSchemaFactory
 * @model kind="package"
 * @generated
 */
public interface AvroSchemaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "avroSchema";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.cohesionforce.com/avro/AvroSchema";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "avroSchema";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AvroSchemaPackage eINSTANCE = com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl.init();

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.AvroSchemaImpl <em>Avro Schema</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getAvroSchema()
   * @generated
   */
  int AVRO_SCHEMA = 0;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVRO_SCHEMA__TYPES = 0;

  /**
   * The number of structural features of the '<em>Avro Schema</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVRO_SCHEMA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.UnionTypeImpl <em>Union Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.UnionTypeImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getUnionType()
   * @generated
   */
  int UNION_TYPE = 1;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION_TYPE__TYPES = 0;

  /**
   * The number of structural features of the '<em>Union Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.UnionMemberImpl <em>Union Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.UnionMemberImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getUnionMember()
   * @generated
   */
  int UNION_MEMBER = 2;

  /**
   * The feature id for the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION_MEMBER__RECORD_REF = 0;

  /**
   * The number of structural features of the '<em>Union Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION_MEMBER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.JsonTypeImpl <em>Json Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.JsonTypeImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getJsonType()
   * @generated
   */
  int JSON_TYPE = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_TYPE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Json Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.RecordImpl <em>Record</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.RecordImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getRecord()
   * @generated
   */
  int RECORD = 4;

  /**
   * The feature id for the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD__RECORD_REF = UNION_MEMBER__RECORD_REF;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD__NAME = UNION_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD__NAMESPACE = UNION_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Field List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD__FIELD_LIST = UNION_MEMBER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Record</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD_FEATURE_COUNT = UNION_MEMBER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.FieldListImpl <em>Field List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.FieldListImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getFieldList()
   * @generated
   */
  int FIELD_LIST = 5;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_LIST__FIELDS = 0;

  /**
   * The number of structural features of the '<em>Field List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.FieldImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getField()
   * @generated
   */
  int FIELD = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Primitive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__PRIMITIVE = 1;

  /**
   * The feature id for the '<em><b>Record</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__RECORD = 2;

  /**
   * The feature id for the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__RECORD_REF = 3;

  /**
   * The feature id for the '<em><b>Etype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__ETYPE = 4;

  /**
   * The feature id for the '<em><b>Array</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__ARRAY = 5;

  /**
   * The feature id for the '<em><b>Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__MAP = 6;

  /**
   * The feature id for the '<em><b>Fixed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__FIXED = 7;

  /**
   * The feature id for the '<em><b>Union</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__UNION = 8;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.EnumTypeImpl <em>Enum Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.EnumTypeImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getEnumType()
   * @generated
   */
  int ENUM_TYPE = 7;

  /**
   * The feature id for the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__RECORD_REF = UNION_MEMBER__RECORD_REF;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__NAME = UNION_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Symbols</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__SYMBOLS = UNION_MEMBER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Enum Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE_FEATURE_COUNT = UNION_MEMBER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.ArrayTypeImpl <em>Array Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.ArrayTypeImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getArrayType()
   * @generated
   */
  int ARRAY_TYPE = 8;

  /**
   * The feature id for the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_TYPE__RECORD_REF = UNION_MEMBER__RECORD_REF;

  /**
   * The feature id for the '<em><b>Primitive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_TYPE__PRIMITIVE = UNION_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Record</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_TYPE__RECORD = UNION_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Etype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_TYPE__ETYPE = UNION_MEMBER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Array Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_TYPE_FEATURE_COUNT = UNION_MEMBER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.MapTypeImpl <em>Map Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.MapTypeImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getMapType()
   * @generated
   */
  int MAP_TYPE = 9;

  /**
   * The feature id for the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_TYPE__RECORD_REF = UNION_MEMBER__RECORD_REF;

  /**
   * The feature id for the '<em><b>Primitive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_TYPE__PRIMITIVE = UNION_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Record</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_TYPE__RECORD = UNION_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Etype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_TYPE__ETYPE = UNION_MEMBER_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Atype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_TYPE__ATYPE = UNION_MEMBER_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Map Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_TYPE_FEATURE_COUNT = UNION_MEMBER_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.FixedTypeImpl <em>Fixed Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.FixedTypeImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getFixedType()
   * @generated
   */
  int FIXED_TYPE = 10;

  /**
   * The feature id for the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIXED_TYPE__RECORD_REF = UNION_MEMBER__RECORD_REF;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIXED_TYPE__NAME = UNION_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIXED_TYPE__SIZE = UNION_MEMBER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fixed Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIXED_TYPE_FEATURE_COUNT = UNION_MEMBER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.cohesionforce.avro.avroSchema.impl.PrimitiveImpl <em>Primitive</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.avro.avroSchema.impl.PrimitiveImpl
   * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getPrimitive()
   * @generated
   */
  int PRIMITIVE = 11;

  /**
   * The feature id for the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE__RECORD_REF = UNION_MEMBER__RECORD_REF;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE__TYPE = UNION_MEMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Primitive</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_FEATURE_COUNT = UNION_MEMBER_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.AvroSchema <em>Avro Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Avro Schema</em>'.
   * @see com.cohesionforce.avro.avroSchema.AvroSchema
   * @generated
   */
  EClass getAvroSchema();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.avro.avroSchema.AvroSchema#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see com.cohesionforce.avro.avroSchema.AvroSchema#getTypes()
   * @see #getAvroSchema()
   * @generated
   */
  EReference getAvroSchema_Types();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.UnionType <em>Union Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Union Type</em>'.
   * @see com.cohesionforce.avro.avroSchema.UnionType
   * @generated
   */
  EClass getUnionType();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.avro.avroSchema.UnionType#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see com.cohesionforce.avro.avroSchema.UnionType#getTypes()
   * @see #getUnionType()
   * @generated
   */
  EReference getUnionType_Types();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.UnionMember <em>Union Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Union Member</em>'.
   * @see com.cohesionforce.avro.avroSchema.UnionMember
   * @generated
   */
  EClass getUnionMember();

  /**
   * Returns the meta object for the reference '{@link com.cohesionforce.avro.avroSchema.UnionMember#getRecordRef <em>Record Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Record Ref</em>'.
   * @see com.cohesionforce.avro.avroSchema.UnionMember#getRecordRef()
   * @see #getUnionMember()
   * @generated
   */
  EReference getUnionMember_RecordRef();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.JsonType <em>Json Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Type</em>'.
   * @see com.cohesionforce.avro.avroSchema.JsonType
   * @generated
   */
  EClass getJsonType();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.JsonType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see com.cohesionforce.avro.avroSchema.JsonType#getType()
   * @see #getJsonType()
   * @generated
   */
  EReference getJsonType_Type();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.Record <em>Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Record</em>'.
   * @see com.cohesionforce.avro.avroSchema.Record
   * @generated
   */
  EClass getRecord();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.avro.avroSchema.Record#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.avro.avroSchema.Record#getName()
   * @see #getRecord()
   * @generated
   */
  EAttribute getRecord_Name();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.avro.avroSchema.Record#getNamespace <em>Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Namespace</em>'.
   * @see com.cohesionforce.avro.avroSchema.Record#getNamespace()
   * @see #getRecord()
   * @generated
   */
  EAttribute getRecord_Namespace();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.Record#getFieldList <em>Field List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Field List</em>'.
   * @see com.cohesionforce.avro.avroSchema.Record#getFieldList()
   * @see #getRecord()
   * @generated
   */
  EReference getRecord_FieldList();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.FieldList <em>Field List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field List</em>'.
   * @see com.cohesionforce.avro.avroSchema.FieldList
   * @generated
   */
  EClass getFieldList();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.avro.avroSchema.FieldList#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see com.cohesionforce.avro.avroSchema.FieldList#getFields()
   * @see #getFieldList()
   * @generated
   */
  EReference getFieldList_Fields();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.avro.avroSchema.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.Field#getPrimitive <em>Primitive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Primitive</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getPrimitive()
   * @see #getField()
   * @generated
   */
  EReference getField_Primitive();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.Field#getRecord <em>Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Record</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getRecord()
   * @see #getField()
   * @generated
   */
  EReference getField_Record();

  /**
   * Returns the meta object for the reference '{@link com.cohesionforce.avro.avroSchema.Field#getRecordRef <em>Record Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Record Ref</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getRecordRef()
   * @see #getField()
   * @generated
   */
  EReference getField_RecordRef();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.Field#getEtype <em>Etype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Etype</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getEtype()
   * @see #getField()
   * @generated
   */
  EReference getField_Etype();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.Field#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Array</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getArray()
   * @see #getField()
   * @generated
   */
  EReference getField_Array();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.Field#getMap <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Map</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getMap()
   * @see #getField()
   * @generated
   */
  EReference getField_Map();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.Field#getFixed <em>Fixed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fixed</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getFixed()
   * @see #getField()
   * @generated
   */
  EReference getField_Fixed();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.Field#getUnion <em>Union</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Union</em>'.
   * @see com.cohesionforce.avro.avroSchema.Field#getUnion()
   * @see #getField()
   * @generated
   */
  EReference getField_Union();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.EnumType <em>Enum Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Type</em>'.
   * @see com.cohesionforce.avro.avroSchema.EnumType
   * @generated
   */
  EClass getEnumType();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.avro.avroSchema.EnumType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.avro.avroSchema.EnumType#getName()
   * @see #getEnumType()
   * @generated
   */
  EAttribute getEnumType_Name();

  /**
   * Returns the meta object for the attribute list '{@link com.cohesionforce.avro.avroSchema.EnumType#getSymbols <em>Symbols</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Symbols</em>'.
   * @see com.cohesionforce.avro.avroSchema.EnumType#getSymbols()
   * @see #getEnumType()
   * @generated
   */
  EAttribute getEnumType_Symbols();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.ArrayType <em>Array Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Type</em>'.
   * @see com.cohesionforce.avro.avroSchema.ArrayType
   * @generated
   */
  EClass getArrayType();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.ArrayType#getPrimitive <em>Primitive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Primitive</em>'.
   * @see com.cohesionforce.avro.avroSchema.ArrayType#getPrimitive()
   * @see #getArrayType()
   * @generated
   */
  EReference getArrayType_Primitive();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.ArrayType#getRecord <em>Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Record</em>'.
   * @see com.cohesionforce.avro.avroSchema.ArrayType#getRecord()
   * @see #getArrayType()
   * @generated
   */
  EReference getArrayType_Record();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.ArrayType#getEtype <em>Etype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Etype</em>'.
   * @see com.cohesionforce.avro.avroSchema.ArrayType#getEtype()
   * @see #getArrayType()
   * @generated
   */
  EReference getArrayType_Etype();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.MapType <em>Map Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map Type</em>'.
   * @see com.cohesionforce.avro.avroSchema.MapType
   * @generated
   */
  EClass getMapType();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.MapType#getPrimitive <em>Primitive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Primitive</em>'.
   * @see com.cohesionforce.avro.avroSchema.MapType#getPrimitive()
   * @see #getMapType()
   * @generated
   */
  EReference getMapType_Primitive();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.MapType#getRecord <em>Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Record</em>'.
   * @see com.cohesionforce.avro.avroSchema.MapType#getRecord()
   * @see #getMapType()
   * @generated
   */
  EReference getMapType_Record();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.MapType#getEtype <em>Etype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Etype</em>'.
   * @see com.cohesionforce.avro.avroSchema.MapType#getEtype()
   * @see #getMapType()
   * @generated
   */
  EReference getMapType_Etype();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.avro.avroSchema.MapType#getAtype <em>Atype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atype</em>'.
   * @see com.cohesionforce.avro.avroSchema.MapType#getAtype()
   * @see #getMapType()
   * @generated
   */
  EReference getMapType_Atype();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.FixedType <em>Fixed Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fixed Type</em>'.
   * @see com.cohesionforce.avro.avroSchema.FixedType
   * @generated
   */
  EClass getFixedType();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.avro.avroSchema.FixedType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.avro.avroSchema.FixedType#getName()
   * @see #getFixedType()
   * @generated
   */
  EAttribute getFixedType_Name();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.avro.avroSchema.FixedType#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see com.cohesionforce.avro.avroSchema.FixedType#getSize()
   * @see #getFixedType()
   * @generated
   */
  EAttribute getFixedType_Size();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.avro.avroSchema.Primitive <em>Primitive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primitive</em>'.
   * @see com.cohesionforce.avro.avroSchema.Primitive
   * @generated
   */
  EClass getPrimitive();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.avro.avroSchema.Primitive#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see com.cohesionforce.avro.avroSchema.Primitive#getType()
   * @see #getPrimitive()
   * @generated
   */
  EAttribute getPrimitive_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AvroSchemaFactory getAvroSchemaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.AvroSchemaImpl <em>Avro Schema</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getAvroSchema()
     * @generated
     */
    EClass AVRO_SCHEMA = eINSTANCE.getAvroSchema();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AVRO_SCHEMA__TYPES = eINSTANCE.getAvroSchema_Types();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.UnionTypeImpl <em>Union Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.UnionTypeImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getUnionType()
     * @generated
     */
    EClass UNION_TYPE = eINSTANCE.getUnionType();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNION_TYPE__TYPES = eINSTANCE.getUnionType_Types();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.UnionMemberImpl <em>Union Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.UnionMemberImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getUnionMember()
     * @generated
     */
    EClass UNION_MEMBER = eINSTANCE.getUnionMember();

    /**
     * The meta object literal for the '<em><b>Record Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNION_MEMBER__RECORD_REF = eINSTANCE.getUnionMember_RecordRef();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.JsonTypeImpl <em>Json Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.JsonTypeImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getJsonType()
     * @generated
     */
    EClass JSON_TYPE = eINSTANCE.getJsonType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_TYPE__TYPE = eINSTANCE.getJsonType_Type();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.RecordImpl <em>Record</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.RecordImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getRecord()
     * @generated
     */
    EClass RECORD = eINSTANCE.getRecord();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECORD__NAME = eINSTANCE.getRecord_Name();

    /**
     * The meta object literal for the '<em><b>Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECORD__NAMESPACE = eINSTANCE.getRecord_Namespace();

    /**
     * The meta object literal for the '<em><b>Field List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECORD__FIELD_LIST = eINSTANCE.getRecord_FieldList();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.FieldListImpl <em>Field List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.FieldListImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getFieldList()
     * @generated
     */
    EClass FIELD_LIST = eINSTANCE.getFieldList();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD_LIST__FIELDS = eINSTANCE.getFieldList_Fields();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.FieldImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '<em><b>Primitive</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__PRIMITIVE = eINSTANCE.getField_Primitive();

    /**
     * The meta object literal for the '<em><b>Record</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__RECORD = eINSTANCE.getField_Record();

    /**
     * The meta object literal for the '<em><b>Record Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__RECORD_REF = eINSTANCE.getField_RecordRef();

    /**
     * The meta object literal for the '<em><b>Etype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__ETYPE = eINSTANCE.getField_Etype();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__ARRAY = eINSTANCE.getField_Array();

    /**
     * The meta object literal for the '<em><b>Map</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__MAP = eINSTANCE.getField_Map();

    /**
     * The meta object literal for the '<em><b>Fixed</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__FIXED = eINSTANCE.getField_Fixed();

    /**
     * The meta object literal for the '<em><b>Union</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__UNION = eINSTANCE.getField_Union();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.EnumTypeImpl <em>Enum Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.EnumTypeImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getEnumType()
     * @generated
     */
    EClass ENUM_TYPE = eINSTANCE.getEnumType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_TYPE__NAME = eINSTANCE.getEnumType_Name();

    /**
     * The meta object literal for the '<em><b>Symbols</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_TYPE__SYMBOLS = eINSTANCE.getEnumType_Symbols();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.ArrayTypeImpl <em>Array Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.ArrayTypeImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getArrayType()
     * @generated
     */
    EClass ARRAY_TYPE = eINSTANCE.getArrayType();

    /**
     * The meta object literal for the '<em><b>Primitive</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_TYPE__PRIMITIVE = eINSTANCE.getArrayType_Primitive();

    /**
     * The meta object literal for the '<em><b>Record</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_TYPE__RECORD = eINSTANCE.getArrayType_Record();

    /**
     * The meta object literal for the '<em><b>Etype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_TYPE__ETYPE = eINSTANCE.getArrayType_Etype();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.MapTypeImpl <em>Map Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.MapTypeImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getMapType()
     * @generated
     */
    EClass MAP_TYPE = eINSTANCE.getMapType();

    /**
     * The meta object literal for the '<em><b>Primitive</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_TYPE__PRIMITIVE = eINSTANCE.getMapType_Primitive();

    /**
     * The meta object literal for the '<em><b>Record</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_TYPE__RECORD = eINSTANCE.getMapType_Record();

    /**
     * The meta object literal for the '<em><b>Etype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_TYPE__ETYPE = eINSTANCE.getMapType_Etype();

    /**
     * The meta object literal for the '<em><b>Atype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_TYPE__ATYPE = eINSTANCE.getMapType_Atype();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.FixedTypeImpl <em>Fixed Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.FixedTypeImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getFixedType()
     * @generated
     */
    EClass FIXED_TYPE = eINSTANCE.getFixedType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIXED_TYPE__NAME = eINSTANCE.getFixedType_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIXED_TYPE__SIZE = eINSTANCE.getFixedType_Size();

    /**
     * The meta object literal for the '{@link com.cohesionforce.avro.avroSchema.impl.PrimitiveImpl <em>Primitive</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.avro.avroSchema.impl.PrimitiveImpl
     * @see com.cohesionforce.avro.avroSchema.impl.AvroSchemaPackageImpl#getPrimitive()
     * @generated
     */
    EClass PRIMITIVE = eINSTANCE.getPrimitive();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIMITIVE__TYPE = eINSTANCE.getPrimitive_Type();

  }

} //AvroSchemaPackage
