/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.avroSchema;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getName <em>Name</em>}</li>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getPrimitive <em>Primitive</em>}</li>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getRecord <em>Record</em>}</li>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getRecordRef <em>Record Ref</em>}</li>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getEtype <em>Etype</em>}</li>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getArray <em>Array</em>}</li>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getMap <em>Map</em>}</li>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getFixed <em>Fixed</em>}</li>
 *   <li>{@link com.cohesionforce.avro.avroSchema.Field#getUnion <em>Union</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField()
 * @model
 * @generated
 */
public interface Field extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Primitive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primitive</em>' containment reference.
   * @see #setPrimitive(Primitive)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_Primitive()
   * @model containment="true"
   * @generated
   */
  Primitive getPrimitive();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getPrimitive <em>Primitive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primitive</em>' containment reference.
   * @see #getPrimitive()
   * @generated
   */
  void setPrimitive(Primitive value);

  /**
   * Returns the value of the '<em><b>Record</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record</em>' containment reference.
   * @see #setRecord(Record)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_Record()
   * @model containment="true"
   * @generated
   */
  Record getRecord();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getRecord <em>Record</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Record</em>' containment reference.
   * @see #getRecord()
   * @generated
   */
  void setRecord(Record value);

  /**
   * Returns the value of the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record Ref</em>' reference.
   * @see #setRecordRef(Record)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_RecordRef()
   * @model
   * @generated
   */
  Record getRecordRef();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getRecordRef <em>Record Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Record Ref</em>' reference.
   * @see #getRecordRef()
   * @generated
   */
  void setRecordRef(Record value);

  /**
   * Returns the value of the '<em><b>Etype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Etype</em>' containment reference.
   * @see #setEtype(EnumType)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_Etype()
   * @model containment="true"
   * @generated
   */
  EnumType getEtype();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getEtype <em>Etype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Etype</em>' containment reference.
   * @see #getEtype()
   * @generated
   */
  void setEtype(EnumType value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' containment reference.
   * @see #setArray(ArrayType)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_Array()
   * @model containment="true"
   * @generated
   */
  ArrayType getArray();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getArray <em>Array</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' containment reference.
   * @see #getArray()
   * @generated
   */
  void setArray(ArrayType value);

  /**
   * Returns the value of the '<em><b>Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map</em>' containment reference.
   * @see #setMap(MapType)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_Map()
   * @model containment="true"
   * @generated
   */
  MapType getMap();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getMap <em>Map</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map</em>' containment reference.
   * @see #getMap()
   * @generated
   */
  void setMap(MapType value);

  /**
   * Returns the value of the '<em><b>Fixed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fixed</em>' containment reference.
   * @see #setFixed(FixedType)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_Fixed()
   * @model containment="true"
   * @generated
   */
  FixedType getFixed();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getFixed <em>Fixed</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fixed</em>' containment reference.
   * @see #getFixed()
   * @generated
   */
  void setFixed(FixedType value);

  /**
   * Returns the value of the '<em><b>Union</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Union</em>' containment reference.
   * @see #setUnion(UnionType)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getField_Union()
   * @model containment="true"
   * @generated
   */
  UnionType getUnion();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.Field#getUnion <em>Union</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Union</em>' containment reference.
   * @see #getUnion()
   * @generated
   */
  void setUnion(UnionType value);

} // Field
