/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.avroSchema;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Union Member</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.avro.avroSchema.UnionMember#getRecordRef <em>Record Ref</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getUnionMember()
 * @model
 * @generated
 */
public interface UnionMember extends EObject
{
  /**
   * Returns the value of the '<em><b>Record Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record Ref</em>' reference.
   * @see #setRecordRef(Record)
   * @see com.cohesionforce.avro.avroSchema.AvroSchemaPackage#getUnionMember_RecordRef()
   * @model
   * @generated
   */
  Record getRecordRef();

  /**
   * Sets the value of the '{@link com.cohesionforce.avro.avroSchema.UnionMember#getRecordRef <em>Record Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Record Ref</em>' reference.
   * @see #getRecordRef()
   * @generated
   */
  void setRecordRef(Record value);

} // UnionMember
