/**
 * generated by Xtext 2.19.0
 */
package com.cohesionforce.avro.tests;

import com.cohesionforce.avro.avroSchema.AvroSchema;
import com.cohesionforce.avro.tests.AvroSchemaInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(AvroSchemaInjectorProvider.class)
@SuppressWarnings("all")
public class AvroSchemaParsingTest {
  @Inject
  private ParseHelper<AvroSchema> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("{\"type\":\"record\",\"name\":\"Addressable\",\"namespace\":\"org.eclipse.emf.examples.extlibrary.avro\",\"fields\":[");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("{\"name\":\"address\",\"type\":[\"null\",\"string\"]}");
      _builder.newLine();
      _builder.append("]}");
      _builder.newLine();
      final AvroSchema result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
